spring:
  application:
    name: board_practice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/practice_db
    username: root
    password: 1234
  mvc:
    hiddenmethod:
      filter:
        enabled: true
        
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
  - mapper/**/*.xml
  
logging:
  file:
    name: ./logs/app.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"