spring:
 application:
  name: jsy_proj
 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/mybatis_proj_db
  username: root
  password: 1234
 mvc:
  hiddenmethod:
    filter:
      enabled: true
 resources:
  web:
    resources:
      static-locations:
        - file:/C:/Users/WD/movieImage/
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapper/**/*.xml