spring:
 application:
  name: board
 datasource:
  driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  url: jdbc:log4jdbc:mysql://localhost:3306/board_db
  username: root
  password: 1234

mybatis:
 mapper-locations: mapper/**/*.xml
 configuration:
  map-underscore-to-camel-case: true

logging:
 level:
  jdbc:
   sqlonly: INFO
   resultsettable: INFO
   sqltiming: off
   resultset: off
   audit: off
   connection: off