spring:
  application:
    name:
      rest_blog
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_blog_db
    username: root
    password: 1234
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false
  sql:
    init:
      mode: never
  mvc:
    hiddenmethod:
       filter:
        enabled: true
  upload:
    location: C:\\Users\\WD\\Desktop\\blogImage
jwt:
  issuer: kosta-seoyeon
  secret_key: myscretmyscretmyscretmyscretmyscret
  access_duration: 1800000 # 30분 (30*60*1000)